apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram-alerts
    group_by:
      - grafana_folder
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: telegram-alerts
        object_matchers:
          - ["severity", "=", "critical"]
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 4h
        continue: false
      - receiver: telegram-alerts
        object_matchers:
          - ["severity", "=", "warning"]
        group_wait: 30s
        group_interval: 10m
        repeat_interval: 12h
        continue: false

